# .readthedocs.yaml
# Read the Docs configuration file

version: 2

sphinx:
   configuration: documentation/conf.py

python:
  version: "3.8"
  install:
    - requirements: requirements.txt
